### ISSUE TITLE
Why job exec request perform within transaction control ?

### ISSUE THREAD

**Issue by kazuki43zoo** [terasoluna-batch/v5-fw#4]
## Description
I want to know a reason that job exec request perform within transaction control.

See https://github.com/terasoluna-batch/v5-fw/blob/master/terasoluna-batch/src/main/java/org/terasoluna/batch/async/db/JobRequestPollTask.java#L194-L216.

Is need a transaction control in this case ? For support the pessimistic locking ? 

## Possible Solutions

I think it not need because a subsequence processing use the optimistic locking (will include `polling_status` as actual job executing conditions).
What do you think ?

## Affects Version/s
* 5.0.0.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yggd** [comment]
As for the point "Why job exec request perform within transaction control ?", it can be read in the following two ways, so I will answer in order.

* Question about the timing of transaction control, i.e., do we not maintain transaction until polling data acquisition and job completion?
* You may think that there is no need to bother with transaction control for polling status changes.

#### Question about the timing of transaction control, i.e., do we not maintain transaction until polling data acquisition and job completion?

This is because we can foresee some inconveniences caused by prolonged transactions for status changes after polling.
For example, if a polled job causes an error, the polled completion status is rolled back, but this behavior may cause a job to be polled again when it is known that the error will recur, or if a job is delayed in completion, the polling interval may need to be controlled so that the next poll does not cause version overtaking or multiple execution.

#### You may think that there is no need to bother with transaction control for polling status changes.

The reason why transaction control is used, even temporarily, is that different RDBMSs have different mechanisms for acquiring locks, and relying on implicit `autocommit' or locking mechanisms of RDBMSs that do not use transactions may cause problems due to differences in behavior specific to RDBMS products. This is because there is a risk of causing problems due to differences in the behavior of RDBMS products.
Therefore, we use explicit declarative transaction control for status changes, even though they are short-lived.
